GET http://localhost:5000/test

###

GET http://localhost:5000/monte_carlo?runs=100000

###

GET http://localhost:5000/monte_carlo?runs=100

###

GET http://localhost:5000/monte_carlo/approximation_of_the_figure_field?runs=1000&points_coordinates={ "points_coordinates": [ [0, 0], [2, 2],  [6, 1], [8, 0] ] }